export const EndPoints = {
  login: "/user/login",
  changePassword: "/user/change/password",
  createUser: "/user/create",
  roles: "/role/all",
  roleExceptSuperAdminAndAgencyemployee:
    "/role/except/superadmin/agencyemployee",
  roleExceptGroupAdmin: "/role/except/groupadmin",
  agences: "/agence/get",
  listUser: "/user/get/all",
  enableOrDisableUser: "/user/disable/enable/{userId}",
  generatePwd: "/user/generate/password/{userId}",
  updateUser: "/user/update",
  userInfo: "/user/get/user/{userId}",
  profilUser: "/user/profile",
  createAgence: "/agence/add",
  updateAgence: "/agence/update/{agenceId}",
  listAgence: "/agence/list",
  infoAgence: "/agence/get/{agenceId}",
  agencyUsers: "/user/agency",
  initTransfert: "/transfert/user/init",
  pendingTransfert: "/transfert/user/pending",
  acceptTransfert: "/transfert/user/accept/{userId}",
  rejectTransfert: "/transfert/user/refuse/{userId}",
  historyTransfert: "/transfert/user/historic",
  historyTransfertAgence: "/transfert/user/historic/agence",
  getUserByChefagence: "/user/get/users/chef/agence",
  addPoste: "/workstation/add",
  listePoste: "/workstation/list",
  updatePoste: "/workstation/update",
  infoPoste: "workstation/info/{workId}",
  chefAgenceUser: "/user/list/users/agence",
  assignWorkStation: "/user/workstation/init",
  assignList: "/user/workstation/list",
  posteNotBusy: "/workstation/not/busy",
  userNotAssign: "/user/list/users/not/assign",
  disableAssgin: "/user/workstation/disable/{userWorkStationId}",
  whatsappConnection: "/whatsapp/link-qrcode",
  whatsappConnectionState: "/whatsapp/connected",
};
